'use client'
import {useState} from 'react'
import {ArrowRight,BarChart3,BookOpen,Check,ChevronDown,CloudUpload,Menu,Search,ShoppingBag,Tags,X,Zap} from 'lucide-react'

const genres=['All books','Fiction','Mystery','Science Fiction','Romance','Non Fiction','Local Authors']
const books=[['The Quiet Map','Mara Bell','$18.00','In Stock','Fiction','bg-[#bd6d52]'],['Night Orchard','Theo Ames','$14.99','2 left','Mystery','bg-[#203d30]'],['Orbit of Dust','Inez Park','$22.00','Pre order','Science Fiction','bg-[#324f69]'],['Small Miracles','June Ellis','$16.50','In Stock','Romance','bg-[#9a6066]'],['Field Notes','Robin Hale','$24.00','In Stock','Non Fiction','bg-[#977541]'],['River City','A. Moreno','$12.99','2 left','Local Authors','bg-[#63527c]'],['Gathering Moss','Lena Ford','$19.00','In Stock','Fiction','bg-[#55705c]'],['Paper Moons','Samira Cole','$8.99','Pre order','Fiction','bg-[#a44e38]']]
const faqs=[['Can I import my current inventory?','Yes. Upload a CSV with titles, authors, ISBNs, prices, stock, genres, descriptions, and cover links. BookShelf validates every row before anything goes live.'],['Do I need to know how to code?','No. Guided setup and catalog controls are designed for bookstore teams, not developers.'],['What happens when a book sells?','Stock updates in the admin dashboard and customer storefront together, helping you avoid selling the same copy twice.'],['Can I connect my payment provider?','Professional plans include Square and Stripe support. Enterprise customers can also use the API for custom workflows.']]
type Book=typeof books[number]
function Cover({b,small=false}:{b:Book,small?:boolean}){return <article><div className={`${b[5]} ${small?'h-28':'h-48 lg:h-56'} relative rounded-md p-3 text-white shadow-[0_12px_25px_#20191229] transition hover:-translate-y-1`}><div className="absolute inset-2 border border-white/25"/><p className="relative font-serif text-lg leading-tight">{b[0]}</p><p className="absolute bottom-3 text-[9px] uppercase tracking-[.2em] text-white/70">{b[1]}</p></div>{!small&&<><h3 className="mt-3 truncate font-semibold">{b[0]}</h3><p className="text-xs text-muted">{b[1]}</p><div className="mt-2 flex justify-between font-mono text-xs"><span>{b[2]}</span><span className="text-brand">{b[3]}</span></div></>}</article>}

export default function Home(){const[menu,setMenu]=useState(false),[genre,setGenre]=useState('All books'),[faq,setFaq]=useState(0);const nav=[['Product','product'],['Features','features'],['Pricing','pricing'],['Stories','stories']];const shown=genre==='All books'?books.slice(0,4):books.filter(b=>b[4]===genre)
return <main className="overflow-hidden">
<nav className="sticky top-0 z-50 border-b bg-paper/90 backdrop-blur-xl"><div className="mx-auto flex h-18 max-w-7xl items-center justify-between px-5 lg:px-8"><a href="#top" className="flex items-center gap-2 font-serif text-2xl font-bold"><span className="grid size-9 place-items-center rounded-md bg-brand text-paper"><BookOpen size={19}/></span>BookShelf</a><div className="hidden gap-8 text-sm md:flex">{nav.map(n=><a key={n[1]} href={'#'+n[1]}>{n[0]}</a>)}</div><a href="#pricing" className="hidden rounded-md bg-brand px-5 py-3 text-sm font-semibold text-paper md:block">Start Your Free Catalog</a><button aria-label="Toggle menu" className="md:hidden" onClick={()=>setMenu(!menu)}>{menu?<X/>:<Menu/>}</button></div><div className={`absolute top-full w-full border-b bg-paper px-5 py-6 transition-all duration-500 ease-[cubic-bezier(0.16,1,0.3,1)] md:hidden ${menu?'pointer-events-auto translate-y-0 opacity-100':'pointer-events-none -translate-y-4 opacity-0'}`}>{nav.map((n,i)=><a onClick={()=>setMenu(false)} style={{transitionDelay:menu?`${i*60}ms`:'0ms'}} className="block border-b py-4 transition-all" key={n[1]} href={'#'+n[1]}>{n[0]}</a>)}</div></nav>

<header id="top" className="mx-auto grid min-h-[720px] max-w-7xl items-center gap-12 px-5 py-20 lg:grid-cols-2 lg:px-8"><div><p className="eyebrow">Built for independent booksellers</p><h1 className="font-serif text-6xl leading-[.9] font-semibold tracking-[-.045em] md:text-7xl xl:text-[82px]">Your Independent Bookstore, <em className="font-normal text-brand">Online in Minutes</em></h1><p className="mt-8 max-w-xl text-xl text-muted">Manage inventory, showcase covers, sell direct. No coding required.</p><div className="mt-10 flex flex-wrap items-center gap-6"><a href="#pricing" className="flex items-center gap-2 rounded-md bg-brand px-6 py-4 font-semibold text-paper">Start Your Free Catalog <ArrowRight size={18}/></a><a href="#product" className="border-b border-brand pb-1 font-semibold text-brand">See Live Demo</a></div></div><div className="relative rounded-xl border bg-white p-3 shadow-2xl"><div className="flex justify-between border-b p-3"><span className="text-[#c17a5c]">● ● ●</span><span className="font-mono text-[9px]">THE TURNING LEAF / CATALOG</span></div><div className="grid grid-cols-[90px_1fr] gap-3 p-3"><aside className="rounded bg-[#f4f0e9] p-3"><Search size={14}/><p className="mt-5 text-[9px] font-bold">GENRES</p>{genres.slice(1,5).map(x=><p key={x} className="mt-2 text-[8px] text-muted">{x}</p>)}</aside><div className="grid grid-cols-3 gap-3">{books.slice(0,6).map(b=><Cover key={b[0]} b={b} small/>)}</div></div></div></header>

<section className="bg-brand text-paper"><div className="mx-auto grid max-w-7xl grid-cols-2 px-5 py-8 md:grid-cols-5">{[['2,847','Books listed on average'],['156','Independent stores'],['98.7%','Inventory accuracy'],['48 hours','Onboarding target'],['Zero fees','First 100 books']].map(s=><div className="border-r border-white/20 px-4 py-4" key={s[0]}><p className="font-mono text-lg font-bold">{s[0]}</p><p className="text-xs text-white/60">{s[1]}</p></div>)}</div></section>

<section id="product" className="section"><div className="split-title"><div><p className="eyebrow">Customer storefront</p><h2>Browsing that feels like a favorite bookshop.</h2></div><p>Help readers find their next book by genre while seeing clear prices and real stock at a glance.</p></div><div className="mt-12 rounded-xl border bg-white p-5 shadow-xl"><div className="mb-6 flex flex-wrap gap-2">{genres.map(g=><button onClick={()=>setGenre(g)} key={g} className={`rounded-full border px-4 py-2 text-xs ${genre===g?'bg-brand text-white':'bg-paper'}`}>{g}</button>)}</div><div className="grid min-h-72 grid-cols-2 gap-5 md:grid-cols-4">{shown.map(b=><Cover key={b[0]} b={b}/>)}</div></div></section>

<section id="features" className="bg-[#eee9e1] py-28"><div className="section !py-0"><p className="eyebrow">One calm workspace</p><h2>Every title, sale, and shelf in sync.</h2><div className="mt-14 grid gap-5 lg:grid-cols-12"><div className="bento lg:col-span-7 lg:row-span-2"><CloudUpload/><h3>Bulk upload, without the cleanup headache.</h3><p>Import 100 or more books with validation and cover mapping. Fix flagged rows before publishing.</p><div className="mt-8 rounded-lg border bg-white p-4 font-mono text-xs">ISBN · TITLE · STOCK · STATUS<br/><br/>978 04 · Night Orchard · 12 · Ready<br/><br/>978 15 · Paper Moons · 0 · Review</div></div><div className="bento !bg-brand !text-white lg:col-span-5"><Zap/><h3>Real time stock tracking</h3><p className="!text-white/65">A sale in store updates the public catalog instantly.</p><b className="mt-8 block font-mono text-4xl">24 <small className="text-base">copies available</small></b></div><div className="bento lg:col-span-5"><Tags/><h3>Price and promotions</h3><p>Create seasonal offers, discounts, and author spotlight tags.</p></div>{[[ShoppingBag,'Keep customer data','Build direct reader relationships without a marketplace middleman.'],[BarChart3,'Control your margins','Your store remains at the center of every online sale.'],[BookOpen,'Beautiful fast storefront','A responsive catalog tuned for quick browsing.']].map(([I,h,p])=>{const Icon=I as typeof BookOpen;return <div className="bento lg:col-span-4" key={h as string}><Icon/><h3>{h as string}</h3><p>{p as string}</p></div>})}</div></div></section>

<section className="section"><div className="grid items-center gap-14 lg:grid-cols-2"><div className="rounded-xl bg-[#1d241d] p-5 text-white shadow-2xl"><div className="flex justify-between border-b border-white/10 pb-5"><span className="font-serif text-xl">Inventory</span><span className="font-mono text-xs">824 TITLES</span></div>{books.slice(0,5).map((b,i)=><div key={b[0]} className="grid grid-cols-[1fr_70px_30px] border-b border-white/10 py-4 text-sm"><span><b className="block">{b[0]}</b><small className="text-white/45">978 04{i} · {b[1]}</small></span><span className="font-mono">{b[2]}</span><span>{i*3+2}</span></div>)}</div><div><p className="eyebrow">Admin dashboard</p><h2>Know exactly what is on every shelf.</h2><p className="mt-6 text-lg leading-relaxed text-muted">Edit titles, authors, ISBNs, genres, prices, and stock from one precise inventory table.</p></div></div></section>

<section id="pricing" className="bg-brand py-28 text-white"><div className="section !py-0"><div className="text-center"><p className="eyebrow !text-[#d7b09e]">Simple subscriptions</p><h2 className="text-white">Room for every shelf.</h2></div><div className="mt-14 grid overflow-hidden rounded-xl border border-white/15 lg:grid-cols-3">{[{n:'Starter',p:'$49',f:['100 book listings','5GB image storage','Basic genre filtering','Email support','CSV bulk import']},{n:'Professional',p:'$129',f:['500 book listings','50GB image storage','Advanced filters','Priority support','Square and Stripe support'],hot:true},{n:'Enterprise',p:'Custom',f:['5,000 or more listings','Unlimited storage','API access','Account manager','White label option']}].map(t=><article key={t.n} className={`relative border-r border-white/15 p-8 ${t.hot?'bg-white text-ink':'bg-white/[.04]'}`}>{t.hot&&<span className="absolute right-5 rounded-full bg-[#c17a5c] px-3 py-1 text-[10px] text-white">POPULAR CHOICE</span>}<h3 className="font-serif text-3xl">{t.n}</h3><p className="mt-8 font-mono text-4xl font-bold">{t.p}{t.p[0]==='$'&&<small className="text-sm"> / month</small>}</p><a href="#signup" className={`mt-8 block rounded-md border px-5 py-3 text-center font-semibold ${t.hot?'bg-brand text-white':''}`}>{t.n==='Enterprise'?'Talk to Sales':'Choose '+t.n}</a><ul className="mt-8 space-y-4 text-sm">{t.f.map(x=><li className="flex gap-3" key={x}><Check size={17} className="text-[#c17a5c]"/>{x}</li>)}</ul></article>)}</div></div></section>

<section id="stories" className="section"><p className="eyebrow">From behind the counter</p><h2>Independent stores, thriving online.</h2><div className="mt-14 grid gap-5 md:grid-cols-2">{[['BookShelf tripled our online sales in the first month. The interface is so clean that even my 60 year old co owner figured it out immediately.','SC','Sarah Chen','Owner, The Turning Page · Portland OR'],['We started with 200 books and now have 2,100 listed. The CSV import saved us literally 30 hours.','MW','Marcus Williams','Manager, Novel & Nook · Atlanta GA'],['Customers finally see our curated selection online instead of just Amazon listings. It feels like our real store.','ER','Elena Rodriguez','Founder, Libros Locales · Denver CO'],['The inventory sync is a lifesaver. We update stock once, and the website updates instantly. No more overselling.','DK','David Kim','Operations, City Lights Annex · Seattle WA']].map(t=><figure key={t[2]} className="rounded-xl border bg-white p-8"><blockquote className="font-serif text-2xl">“{t[0]}”</blockquote><figcaption className="mt-7 flex gap-3"><span className="grid size-10 place-items-center rounded-full bg-peach font-bold">{t[1]}</span><span className="text-sm"><b className="block">{t[2]}</b><small className="text-muted">{t[3]}</small></span></figcaption></figure>)}</div></section>

<section className="bg-[#eee9e1] py-24"><div className="mx-auto max-w-3xl px-5"><p className="eyebrow">Questions, answered</p><h2>Before you open the doors.</h2><div className="mt-10">{faqs.map((f,i)=><div className="border-b" key={f[0]}><button onClick={()=>setFaq(faq===i?-1:i)} className="flex w-full justify-between py-6 text-left font-semibold">{f[0]}<ChevronDown className={faq===i?'rotate-180':''}/></button><div className={`grid transition-all ${faq===i?'grid-rows-[1fr] pb-6':'grid-rows-[0fr]'}`}><p className="overflow-hidden text-muted">{f[1]}</p></div></div>)}</div></div></section>
<section id="signup" className="px-5 py-24"><div className="mx-auto max-w-7xl rounded-2xl bg-[#c17a5c] px-6 py-16 text-center text-white"><h2 className="text-white">Put your shelves online. Keep your shop unmistakably yours.</h2><p className="mt-5 text-white/75">Create your first catalog and see how simple independent bookselling online can feel.</p><a href="#pricing" className="mt-9 inline-flex items-center gap-2 rounded-md bg-brand px-6 py-4 font-semibold">Start Your Free Catalog <ArrowRight size={18}/></a></div></section>
<footer className="bg-[#171914] text-white"><div className="section !py-14"><p className="font-serif text-3xl">BookShelf</p><p className="mt-3 max-w-sm text-sm text-white/50">The digital catalog built for independent bookstores and the communities they serve.</p><div className="mt-10 flex flex-wrap gap-8 text-sm text-white/60">{nav.map(n=><a key={n[0]} href={'#'+n[1]}>{n[0]}</a>)}</div><p className="mt-12 border-t border-white/10 pt-6 font-mono text-[10px] text-white/35">© 2026 BOOKSHELF · MADE FOR INDEPENDENT BOOKSELLERS</p></div></footer></main>}
